[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32G070KBTx --defmt"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
